import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "EQUILEX",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative">
      <Toaster />
      {children}
    </div>
  );
}
