'use client'

import type { Metadata } from "next";
import "../globals.css";
import MainNavbar from "@/components/mainNavbar";
import LawyerSidebar from "@/components/lawyerSidebar";
import { usePathname } from "next/navigation";
import { NotificationProvider } from "../context/NotificationContext";

// export const metadata: Metadata = {
//   title: "EQUILEX",
//   description: "Generated by create next app",
// };

export default function LawyerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const noSidebarRoutes = [
    "/lawyer/profile",
    /^\/lawyer\/cases\/\d+$/,
    /^\/lawyer\/cases\/\d\/dispute+$/,
    "/lawyer/notification",
    "/lawyer/withdraw",
  ];

  const shouldHideSidebar = (path: string) => {
    return noSidebarRoutes.some((route) =>
      route instanceof RegExp ? route.test(path) : route === path
    );
  };

  return (
    <NotificationProvider>
      <div className="relative">
        <MainNavbar />
        {!shouldHideSidebar(pathname) && <LawyerSidebar />}
        <div className="relative max-w-screen-2xl flex min-h-screen  flex-col bg-background">
          {children}
        </div>
      </div>
    </NotificationProvider>
  );
}
