import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MainNavbar from "@/components/mainNavbar";
import LawyerSidebar from "@/components/lawyerSidebar";
// import MainNavbar from "../../components/MainNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EQUILEX",
  description: "Generated by create next app",
};

export default function LawyerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative">
      <MainNavbar />
      <LawyerSidebar/>
      <div className="relative max-w-screen-2xl flex min-h-screen  flex-col bg-background">
        {children}
      </div>
    </div>
  );
}
