import type { Metadata } from "next";
import "../globals.css";
import MainNavbar from "@/components/mainNavbar";


export const metadata: Metadata = {
  title: "EQUILEX",
  description: "Generated by create next app",
};

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative">
      <MainNavbar />
      <div className="relative max-w-screen-2xl flex min-h-screen  flex-col bg-background">
        {children}
      </div>
    </div>
  );
}
