import type { Metadata } from "next";
import "../globals.css";
import MainNavbar from "@/components/mainNavbar";
// import MainNavbar from "../../components/MainNavbar";


export const metadata: Metadata = {
  title: "EQUILEX",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
        <div className="relative">
          <MainNavbar/>
          <div  className="relative max-w-screen-2xl  min-h-screen">
            {children}
          </div>
        </div>
  );
}
